apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiny-bot
  namespace: education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiny-bot
  template:
    metadata:
      labels:
        app: tiny-bot
    spec:
      containers:
        - name: llama
          image: ghcr.io/ggml-org/llama.cpp:server
          args:
            - "--model"
            - "/models/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8080"
            - "--ctx-size"
            - "2048"         
            - "--threads"
            - "4"            
            - "--n-gpu-layers"
            - "0"            
            - "--temp"
            - "0.7"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - name: models
              mountPath: /models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: skylight-models