apiVersion: batch/v1
kind: Job
metadata:
  name: tiny-model-download
  namespace: education
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: downloader
          image: alpine:3.19
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eux
              apk add --no-cache wget ca-certificates
              mkdir -p /models
              wget -O /models/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf \
                https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
          volumeMounts:
            - name: models
              mountPath: /models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: skylight-models