apiVersion: v1
kind: Service
metadata:
  name: tiny-bot-service
  namespace: education
spec:
  selector:
    app: tiny-bot
  ports:
    - protocol: TCP
      port: 80           
      targetPort: 8080   
  type: ClusterIP